#Training
learning_rate: 0.002
batch_size: 128
weight_decay: 0.01
lr_decay: 0.99
epochs: 90

# Model
model_name: MotionMamba
st_depth: 4
channel: 64
d_state: 16
bimamba_type: v2
if_divide_out: True
n_joints: 17
act_layer: gelu
n_frames: 81
expand: 1

# Data
data_root: data/motion3d/
flip: True
stride: 9
num_joints: 17
out_joints: 17
test_augmentation: True
data_augmentation: True
reverse_augmentation: False
out_all: 1
test_batch_size: 128

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0