#Training
learning_rate: 0.0005
batch_size: 16
weight_decay: 0.01
lr_decay: 0.99
epochs: 120
train_2d: False

# Model
model_name: MotionMamba
st_depth: 8
channel: 64
d_state: 16
bimamba_type: v2
if_divide_out: True
n_joints: 17
dim_out: 3
act_layer: gelu
n_frames: 243
expand: 1

# Data
data_root: data/motion3d/
data_root_2d: data/motion2d/
subset_list: [ H36M-243 ]
dt_file: h36m_sh_conf_cam_source_final.pkl
root_rel: True # Normalizing joints relative to the root joint
add_velocity: False
num_joints: 17
# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
use_proj_as_2d: False   # if use gt 2d, choose True
flip: True